spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create
    database: mysql


  datasource:
    url: jdbc:h2:mem:moin;MODE=MySQL;DATABASE_TO_LOWER=TRUE #mysql 모드 설정
    username: sa
    password: 4432
    driver-class-name: org.h2.Driver


  h2:
    console:
      enabled: true
      path: /h2-console


converter:
  db:
    key: "B9lWvd2$bANXE5mWvGk3XxvWo9MSa#f0"


jwt:
  secret: "zlRUysyWjmjN2O1e831SsspxoJLO0deV3f8QDJ5gjusO88ullKtuyMJ6OFXfE22ideV3f8QDJ5gjusO88ullKtuyMJ6OFXfE22i"